# Generated by Django 5.2 on 2025-05-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('HR', 'Human Resources'), ('Sales', 'Sales'), ('Finance', 'Finance'), ('Marketing', 'Marketing')], default='IT', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.PositiveIntegerField(default=1, help_text='Years of experience required'),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=20000, max_digits=10),
        ),
    ]
